//! Shared SQL identifier vocabulary for configuration and store backends.

/// SQL keywords rejected from unquoted table and column identifiers.
pub(crate) const RESERVED_WORDS: &[&str] = &[
    "select",
    "insert",
    "update",
    "delete",
    "create",
    "drop",
    "alter",
    "table",
    "index",
    "view",
    "trigger",
    "where",
    "from",
    "join",
    "on",
    "and",
    "or",
    "not",
    "null",
    "is",
    "in",
    "like",
    "between",
    "as",
    "order",
    "group",
    "having",
    "limit",
    "offset",
    "union",
    "except",
    "intersect",
    "into",
    "values",
    "set",
    "primary",
    "key",
    "foreign",
    "references",
    "check",
    "default",
    "constraint",
    "unique",
    "cascade",
    "restrict",
    "if",
    "exists",
    "case",
    "when",
    "then",
    "else",
    "end",
    "begin",
    "commit",
    "rollback",
    "transaction",
    "true",
    "false",
    "unknown",
];

/// Return whether an identifier conflicts with a reserved SQL keyword.
pub(crate) fn is_reserved_word(value: &str) -> bool {
    RESERVED_WORDS.contains(&value.to_ascii_lowercase().as_str())
}
